---
name: CPS-Governor-IOAsync
version: 0.01
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: 'use L<IO::Async> with L<CPS>'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  CPS: 0.06
  IO::Async: 0.24
configure_requires:
  Module::Build: 0.35
provides:
  CPS::Governor::IOAsync:
    file: lib/CPS/Governor/IOAsync.pm
    version: 0.01
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
